# Thresholds
object_confidence_threshhold = 0.45 # Out of 1
pose_visibility_threshhold = 0.45 # Out of 1
# Configure the biases for the images recommendation
image_raw_bias_settings = [   
    {'biasamount': 0.1, 'id': 0, 'name': 'person'},
    {'biasamount': 0.2, 'id': 1, 'name': 'bicycle'},
    {'biasamount': 0.1, 'id': 2, 'name': 'car'},
    {'biasamount': 0.2, 'id': 3, 'name': 'motorcycle'},
    {'biasamount': 0.2, 'id': 4, 'name': 'airplane'},
    {'biasamount': 0.2, 'id': 5, 'name': 'bus'},
    {'biasamount': 0.2, 'id': 6, 'name': 'train'},
    {'biasamount': 0.2, 'id': 7, 'name': 'truck'},
    {'biasamount': 0.2, 'id': 8, 'name': 'boat'},
    {'biasamount': 0.1, 'id': 9, 'name': 'traffic light'},
    {'biasamount': 0.1, 'id': 10, 'name': 'fire hydrant'},
    {'biasamount': 0.1, 'id': 11, 'name': 'stop sign'},
    {'biasamount': 0.1, 'id': 12, 'name': 'parking meter'},
    {'biasamount': 0.1, 'id': 13, 'name': 'bench'},
    {'biasamount': 0.1, 'id': 14, 'name': 'bird'},
    {'biasamount': 0.1, 'id': 15, 'name': 'cat'},
    {'biasamount': 0.3, 'id': 16, 'name': 'dog'},
    {'biasamount': 0.4, 'id': 17, 'name': 'horse'},
    {'biasamount': 0.3, 'id': 18, 'name': 'sheep'},
    {'biasamount': 0.3, 'id': 19, 'name': 'cow'},
    {'biasamount': 0.3, 'id': 20, 'name': 'elephant'},
    {'biasamount': 0.3, 'id': 21, 'name': 'bear'},
    {'biasamount': 0.3, 'id': 22, 'name': 'zebra'},
    {'biasamount': 0.3, 'id': 23, 'name': 'giraffe'},
    {'biasamount': 0.1, 'id': 24, 'name': 'backpack'},
    {'biasamount': 0.2, 'id': 25, 'name': 'umbrella'},
    {'biasamount': 0.3, 'id': 26, 'name': 'handbag'},
    {'biasamount': 0.2, 'id': 27, 'name': 'tie'},
    {'biasamount': 0.3, 'id': 28, 'name': 'suitcase'},
    {'biasamount': 0.3, 'id': 29, 'name': 'frisbee'},
    {'biasamount': 0.1, 'id': 30, 'name': 'skis'},
    {'biasamount': 0.1, 'id': 31, 'name': 'snowboard'},
    {'biasamount': 0.5, 'id': 32, 'name': 'sports ball'},
    {'biasamount': 0.4, 'id': 33, 'name': 'kite'},
    {'biasamount': 0.2, 'id': 34, 'name': 'baseball bat'},
    {'biasamount': 0.2, 'id': 35, 'name': 'baseball glove'},
    {'biasamount': 0.3, 'id': 36, 'name': 'skateboard'},
    {'biasamount': 0.1, 'id': 37, 'name': 'surfboard'},
    {'biasamount': 0.3, 'id': 38, 'name': 'tennis racket'},
    {'biasamount': 0.2, 'id': 39, 'name': 'bottle'},
    {'biasamount': 0.1, 'id': 40, 'name': 'wine glass'},
    {'biasamount': 0.2, 'id': 41, 'name': 'cup'},
    {'biasamount': 0.2, 'id': 42, 'name': 'fork'},
    {'biasamount': 0.2, 'id': 43, 'name': 'knife'},
    {'biasamount': 0.2, 'id': 44, 'name': 'spoon'},
    {'biasamount': 0.2, 'id': 45, 'name': 'bowl'},
    {'biasamount': 0.3, 'id': 46, 'name': 'banana'},
    {'biasamount': 0.3, 'id': 47, 'name': 'apple'},
    {'biasamount': 0.3, 'id': 48, 'name': 'sandwich'},
    {'biasamount': 0.2, 'id': 49, 'name': 'orange'},
    {'biasamount': 0.1, 'id': 50, 'name': 'broccoli'},
    {'biasamount': 0.1, 'id': 51, 'name': 'carrot'},
    {'biasamount': 0.2, 'id': 52, 'name': 'hot dog'},
    {'biasamount': 0.2, 'id': 53, 'name': 'pizza'},
    {'biasamount': 0.3, 'id': 54, 'name': 'donut'},
    {'biasamount': 0.2, 'id': 55, 'name': 'cake'},
    {'biasamount': 0.2, 'id': 56, 'name': 'chair'},
    {'biasamount': 0.4, 'id': 57, 'name': 'couch'},
    {'biasamount': 0.2, 'id': 58, 'name': 'potted plant'},
    {'biasamount': 0.2, 'id': 59, 'name': 'bed'},
    {'biasamount': 0.2, 'id': 60, 'name': 'dining table'},
    {'biasamount': 0.1, 'id': 61, 'name': 'toilet'},
    {'biasamount': 0.2, 'id': 62, 'name': 'tv'},
    {'biasamount': 0.4, 'id': 63, 'name': 'laptop'},
    {'biasamount': 0.4, 'id': 64, 'name': 'mouse'},
    {'biasamount': 0.3, 'id': 65, 'name': 'remote'},
    {'biasamount': 0.4, 'id': 66, 'name': 'keyboard'},
    {'biasamount': 0.1, 'id': 67, 'name': 'cell phone'},
    {'biasamount': 0.2, 'id': 68, 'name': 'microwave'},
    {'biasamount': 0.2, 'id': 69, 'name': 'oven'},
    {'biasamount': 0.2, 'id': 70, 'name': 'toaster'},
    {'biasamount': 0.2, 'id': 71, 'name': 'sink'},
    {'biasamount': 0.2, 'id': 72, 'name': 'refrigerator'},
    {'biasamount': 0.2, 'id': 73, 'name': 'book'},
    {'biasamount': 0.2, 'id': 74, 'name': 'clock'},
    {'biasamount': 0.1, 'id': 75, 'name': 'vase'},
    {'biasamount': 0.3, 'id': 76, 'name': 'scissors'},
    {'biasamount': 0.4, 'id': 77, 'name': 'teddy bear'},
    {'biasamount': 0.1, 'id': 78, 'name': 'hair drier'},
    {'biasamount': 0.1, 'id': 79, 'name': 'toothbrush'}]